# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('monthSeason', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=100)),
                ('data', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set([('country', 'monthSeason', 'year', 'type')]),
        ),
    ]
