# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='monthSeason',
            new_name='month_or_season',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='data',
            new_name='reading',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='type',
            new_name='reading_type',
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together=set([('country', 'month_or_season', 'year', 'reading_type')]),
        ),
    ]
